--- #YAML:1.0
name:                IO-Prompter
version:             0.001001
abstract:            Prompt for input, read it, clean it, return it.
license:             ~
author:              
    - Damian Conway <DCONWAY@CPAN.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Contextual::Return:            0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
