--- #YAML:1.0
name:               IO-Prompter
version:            0.004006
abstract:           Prompt for input, read it, clean it, return it.
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Contextual::Return:  0
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
